### ISSUE TITLE
React 16 issue with Text field

### ISSUE THREAD

**Issue by drusellers** [react-tools/react-form#132]
```
Failed form propType: You provided a `value` prop to a form field without an `onChange` handler. This will render a read-only field. If the field should be mutable use `defaultValue`. Otherwise, set either `onChange` or `readOnly`
```

On wonder if its because of the onInput rather than onChange usage.

 https://github.com/react-tools/react-form/blob/master/src/components/form-fields/Text.js#L35

**Comment by drusellers** [comment]
https://stackoverflow.com/a/40003179

**Comment by joepuzzo** [comment]
Can you provide the code that causes this to happen. If i remember correctly, I went with onInput because i noticed that when i had a lot of fields in a huge form on one of my production applications, that the on change was not getting fired, i eventually tracked this down to an issue with using the onChange and updating it to be onInput solved my issue. I am trying to track down the source where i learned this from.

**Comment by drusellers** [comment]
Using `create-react-app` then `yarn add react-form`

I changed the `App.js` to this.

```
import React, { Component } from 'react';
import './App.css';
import { Form, Text } from 'react-form';

class App extends Component {
  render() {
    return (
      <div className="App">
        The console error appears once default value is provided.
        <Form defaultValues={{ bob: 'abc' }}>
          {formApi => {
            return (
              <form onSubmit={formApi.submitForm}>
                <Text field="bob" />
              </form>
            );
          }}
        </Form>
      </div>
    );
  }
}

export default App;
```
