### ISSUE TITLE
accessing formApi on Form prop onSubmit

### ISSUE THREAD

**Issue by AlexandreBernard** [react-tools/react-form#144]
Hi,

I've just seen #139 added access to event object on submit

why not having access to formApi on onSubmit too as we have access to it on formDidUpdate?

I would even suggest replacing the values object by the formApi object as it would just give more flexibility, be more consistent and as it contains values too - but this of course would be a breaking change

the reason why I'm asking this is that for some UI reasons I need to access submitsCount and that to solve my issue I will have to find a more tricky solution

(also I find a bit confusing that we need to have two onSubmit for a single form. and btw the library is great, otherwise I wouldn't spend time commenting)

**Comment by joepuzzo** [comment]
What do you mean by "twoOnSubmit"? And also good idea.. i dont want to introduce breaking changes but i can def make it so third prop is the whole API. The reason I did values is because that was pretty natural for people who just want `onSubmit( values )`.

**Comment by tannerlinsley** [comment]
Imo the form API should be the last method for all prop callbacks. This
alleviates the need for getApi and instance saving.

**Comment by AlexandreBernard** [comment]
Yeah of course it's not possible to release such a breaking change and it's totally natural for most cases to have values as a first parameter. Having it as a third parameter would be great already

I mean this by "double" onSubmit : 

```
<Form onSubmit={submittedValues => this.setState( { submittedValues } )}>
   { formApi => (
       <form onSubmit={formApi.submitForm} id="form2">
       ...
```

**Comment by joepuzzo** [comment]
Ok i will add that param to callback when i get a chance.. and ok i can explain that "double" on submit. So in pure HTML land, `<forms>` have an onSubmit that gets called when a `button` within the `form` with `type='submit'` gets clicked. So, what the `<form onSubmit={formApi.submitForm} id="form2">` is doing, is "wiring up" the native html forms onSubmit, to the forms special `submitForm` function. The second onSubmit 
```
onSubmit={submittedValues => this.setState( { submittedValues } )}
``` 
is a callback that you can pass to the `<Form>`. This is different because this onSubmit will only get called when the forms is valid and all of its lifecyle stuff has been called. 

We still want to keep the forms accessible and stuff, so using the native `<form>` is a good thing.

Side note: 

We could have designed this such that the `<form>` was abstracted away from the user ( was rendered and "wired up" internally ) but this leaves creating custom styles around `<forms>` more difficult.

**Comment by joepuzzo** [comment]
I have added formApi to onSubmit as third param. V2.8.1

**Comment by AlexandreBernard** [comment]
awesome, thanks
