### ISSUE TITLE
Feature Parity: provide a setAllValues formApi method.

### ISSUE THREAD

**Issue by tannerlinsley** [react-tools/react-form#155]
This method would replace all of the form values it's called in. Pretty straight-forward

**Comment by joepuzzo** [comment]
Only part thats not strait forward is for nested forms. The problem is this: If you have a nested forms say `Questions` and you call `setAllValues` with `{ name: 'Joe', questions: { favColor: 'green', favFood: 'pizza' } } ` Then the parent forms store will get populated with the values, but the nested forms will not. As an MVP i could add this to the `formApi` but users will have to be aware of this.

**Comment by joepuzzo** [comment]
in other words if you want to setAllValues on nested forms.. you will have to call the nested forms setAllValues.

**Comment by tannerlinsley** [comment]
I think that's fine. 👍

**Comment by joepuzzo** [comment]
cool

**Comment by joepuzzo** [comment]
This is in.
