### ISSUE TITLE
How to implement setAllTouched in react-form v2?

### ISSUE THREAD

**Issue by jiangweiliu-aa** [react-tools/react-form#157]
I'm upgrading react-form from v1 to v2, I found `setAllTouched` has been removed from v2. I'm wondering of how to implement it in a neat way, instead of running `getTouched` for all field.

**Comment by joepuzzo** [comment]
Yeah my apologies as there are a few features i have yet to port over. I can look into adding this as well as the onValidationFailure.

**Comment by joepuzzo** [comment]
@jiangweiliu-aa i will add this but one thing to be aware of is that `setAllTouched` will NOT set nested forms fields to touched.

**Comment by joepuzzo** [comment]
Ok so i may have to unfortunately change the interface for this. I could get into the dirty details, but basically because of the way nested forms work, it would make it difficult to have a function `setAllTouched(true)` or `setAllTouched(false)` because i cant tell the difference between what is a nested field, and what is not. In the future we want to work toward a solution that takes out this complexity but for now it exists.

Conclusion, i will add this method... but you will unforuntaley have to pass the fields like so `setAllTouched( { foo: true, baz: true } )`. I dont like this but as it stands this is a limitation. I can update this once i have added it.

**Comment by joepuzzo** [comment]
Ok i just put out V2.8.0 and it has setAllTouched the way i talked about above. Again sorry this is the cleanest way i can do this for now. NOTE when you click the submit button everything, INCLUDING NESTED FORMS, get set to touched simply because of the way HTML forms work so keep that in mind as that will generally get you most use cases.

**Comment by jiangweiliu-aa** [comment]
@joepuzzo Thanks for your update, it really saved my life.
