### ISSUE TITLE
Any recommendation on which date picker component to use?

### ISSUE THREAD

**Issue by lynnchin** [react-tools/react-form#165]
Just wondering if there is any recommendation on which date picker component I can use that integrates with the react forms library?

**Comment by joepuzzo** [comment]
Funny u mention this .. i used react date pickee with react form and it worked great.

**Comment by lynnchin** [comment]
hmm alright, I will have a look at react date picker then :dancing_men:

**Comment by joepuzzo** [comment]
I created custom input for this using FormField

**Comment by lynnchin** [comment]
Can I ask which date picker you are using? Is it this one?
http://react-day-picker.js.org/examples/

**Comment by joepuzzo** [comment]
https://hacker0x01.github.io/react-datepicker/

**Comment by JaffParker** [comment]
I'm actually experiencing one tiny, rather annoying than blocking issue with this. I make sure to handle dates with moment all across my app - I try not to allow any string dates. And react-datepicker is perfect for that since the value it returns from the field is a moment object.

But react-form does one little thing on submit that translates it into a string date: 
`let values = JSON.parse(JSON.stringify(this.props.formState.values))`

I can use preSubmit to transform it back into a moment, which is what I have to do, but it would be awesome, if I didn't have to do it...

And unfortunately, that line is posted runs no matter what, it's not a part of a condition.
