### ISSUE TITLE
Array fields aren't updated in a consistent manner

### ISSUE THREAD

**Issue by SBoudrias** [react-tools/react-form#183]
Hey, that's a bug I found using the latest major version and that wasn't an issue in the previous one.

Basically, when using `setValue()` on an Array type field, it won't update in a consistent manner depending on how you access the field:

```js
// Given a form with:
const values = { friends: [] };

// Case 1: update properly
setValue(['friends', 0], 'Simon');
setValue(['friends', 1], 'Jiangwei');
// output: { friends: ['Simon', 'Jiangwei'] }

// Case 2: breaking:
setValue('friends.0', 'Simon');
setValue('friends.1', 'Jiangwei');
// output: { friends: { '0': 'Simon', '1': 'Jiangwei' } }
```

This behavior isn't super obvious, and should likely be modified to prevent confusion.

**Comment by joepuzzo** [comment]
This was a breaking change that is staing in v2. There are many people that requested for this as a feature because some users have unique ids that happen to be numbers, and in v1 we could not support that. There is a very simple work around for this using the correct syntax and all that info can be found uner the “fieldsyntax” tab in the latest docs.
