### ISSUE TITLE
Access touched in validateError?

### ISSUE THREAD

**Issue by reggieofarrell** [react-tools/react-form#201]
As soon as I type in any of the fields the entire form tries to validate.  Is that intended?  I'd like for a field to only validate once it has been touched by I can't find a way to access the touched property for a form field inside of the validateError function.  If I'm completely missing something please let me know.

**Comment by joepuzzo** [comment]
Use the combination of the touched and errors to get what you need.. thats how i do it for all mu projets

**Comment by reggieofarrell** [comment]
Can you give an example?

**Comment by joepuzzo** [comment]
So there is no way to prevent the whole form from validating, the validate function is called every time you interact with an input. This was a design decision because more often than not you want/need the whole form to validate. That being said, just because the form does not let you submit because its invalid, does not mean you cant use the errors and touched together to only show to the user that the field is in an error state. In my code, I have custom inputs that basically only show error `<Messages>` for a field when the following is true ` formApi.errors.fieldName && formApi.touched.fieldName`. Because my guess is that you dont want the user to see a bunch of errors when they have not even interacted with a field yet.

**Comment by joepuzzo** [comment]
@reggieofarrell  Updates on this? Can i close? BTW i added a prop to only validate on submit so this may help here.

**Comment by reggieofarrell** [comment]
Thanks for followIng up. I ended up using Redux on this project so I decided to go with Redux Form.
