### ISSUE TITLE
Custom inputs

### ISSUE THREAD

**Issue by KokoulinM** [react-tools/react-form#234]
warning.js:33 Warning: CustomTextWrapper is changing an uncontrolled input of type undefined to be controlled. Input elements should not switch from uncontrolled to controlled (or vice versa). Decide between using a controlled or uncontrolled input element for the lifetime of the component. More info: https://fb.me/react-controlled-components

How to get rid of the problem?

**Comment by joepuzzo** [comment]
check out the text input and not the `getValue() || ''`. This is how i got rid of the error because when the form first loads the value is null. This error occurs when the value is null and then becomes not null.

https://github.com/react-tools/react-form/blob/master/src/components/form-fields/Text.js

**Comment by KokoulinM** [comment]
Thanks, you!
