### ISSUE TITLE
1.3.0 Rerender causes form to lose values

### ISSUE THREAD

**Issue by timothyallan** [react-tools/react-form#84]
Hey there. 1.2.8 works great, 1.3.0 breaks all my dynamic forms. SAD.

I’ve got a bunch of user text input fields, one which causes an API call to a server to get some data. When that data comes back, an isLoading boolean is changed. Because of that, the page containing the form is re-rendered (which I can see via console.log in the render function).

The text inputs are custom `FormInput` components wrapped around Material UI Textfields.

Until 1.3 this was working great, however now as soon as `render()` is called again, my form loses all it’s values, and `getValue()` returns undefined for everything.

If I disable the page re-render, by not using an isLoading bool, the form retains it’s values, but then I lose all my pretty loading spinners. 

I've looked through the 1.3 updates, but there's nothing immediately obvious that jumps out, any suggestions?

**Comment by Temoto-kun** [comment]
Can confirm this bug. Also happens on mine when I try to disable the form on submit (because it re-renders the view). I lose all the values of the form, but when I tried downgrading to 1.2.8 it somehow retains the values in the view, but then the values aren't included in ordinary form requests. Had to manually re-submit the form on `submitForm()`.

**Comment by joepuzzo** [comment]
Hmm i need to check to see if this is a problem in V2. I don't think it is but I can look into it.

**Comment by tannerlinsley** [comment]
So far so good for me. Going to close for now.
